services:
  - type: web
    name: pentagon-pizza-meter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false 